name: Nix

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Nix building
        run: nix build -L
